// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApp_ASPNET.Data;

#nullable disable

namespace WebApp_ASPNET.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("WebApp_ASPNET.Models.Contact", b =>
                {
                    b.Property<string>("Fullname")
                        .HasMaxLength(71)
                        .HasColumnType("varchar(71)");

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Avatar")
                        .HasMaxLength(2083)
                        .HasColumnType("varchar(2083)");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)");

                    b.Property<DateTime?>("Naissance")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nom")
                        .HasMaxLength(35)
                        .HasColumnType("varchar(35)");

                    b.Property<string>("Prenom")
                        .HasMaxLength(35)
                        .HasColumnType("varchar(35)");

                    b.HasKey("Fullname");

                    b.HasIndex("Genre");

                    b.ToTable("Contact", (string)null);
                });

            modelBuilder.Entity("WebApp_ASPNET.Models.Sexe", b =>
                {
                    b.Property<string>("Genre")
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)");

                    b.HasKey("Genre");

                    b.ToTable("Sexe", (string)null);
                });

            modelBuilder.Entity("WebApp_ASPNET.Models.Contact", b =>
                {
                    b.HasOne("WebApp_ASPNET.Models.Sexe", "Sexe")
                        .WithMany()
                        .HasForeignKey("Genre")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sexe");
                });
#pragma warning restore 612, 618
        }
    }
}
